---
apiVersion: admissionregistration.k8s.io/v1
kind: MutatingWebhookConfiguration
metadata:
  name: mutating-webhook-configuration
webhooks:
- admissionReviewVersions:
  - v1
  clientConfig:
    service:
      name: webhook-service
      namespace: system
      path: /mutate-cloudnative-misskey-dev-v1beta1-misskey
  failurePolicy: Fail
  name: mmisskey-v1beta1.kb.io
  rules:
  - apiGroups:
    - cloudnative-misskey.dev
    apiVersions:
    - v1beta1
    operations:
    - CREATE
    - UPDATE
    resources:
    - misskeys
  sideEffects: None
---
apiVersion: admissionregistration.k8s.io/v1
kind: ValidatingWebhookConfiguration
metadata:
  name: validating-webhook-configuration
webhooks:
- admissionReviewVersions:
  - v1
  clientConfig:
    service:
      name: webhook-service
      namespace: system
      path: /validate-cloudnative-misskey-dev-v1beta1-misskey
  failurePolicy: Fail
  name: vmisskey-v1beta1.kb.io
  rules:
  - apiGroups:
    - cloudnative-misskey.dev
    apiVersions:
    - v1beta1
    operations:
    - CREATE
    - UPDATE
    resources:
    - misskeys
  sideEffects: None
- admissionReviewVersions:
  - v1
  clientConfig:
    service:
      name: webhook-service
      namespace: system
      path: /validate-cloudnative-misskey-dev-v1beta1-misskeychannel
  failurePolicy: Fail
  name: vmisskeychannel-v1beta1.kb.io
  rules:
  - apiGroups:
    - cloudnative-misskey.dev
    apiVersions:
    - v1beta1
    operations:
    - CREATE
    - UPDATE
    resources:
    - misskeychannels
  sideEffects: None
