//go:build !ignore_autogenerated

/*
Copyright (C) 2026 chan-mai

This program is free software: you can redistribute it and/or modify
it under the terms of the GNU Affero General Public License as published by
the Free Software Foundation, either version 3 of the License, or
(at your option) any later version.

This program is distributed in the hope that it will be useful,
but WITHOUT ANY WARRANTY; without even the implied warranty of
MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
GNU Affero General Public License for more details.

You should have received a copy of the GNU Affero General Public License
along with this program.  If not, see <https://www.gnu.org/licenses/>.
*/

// Code generated by controller-gen. DO NOT EDIT.

package v1beta1

import (
	"k8s.io/api/core/v1"
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	runtime "k8s.io/apimachinery/pkg/runtime"
)

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AppAutoscalingSpec) DeepCopyInto(out *AppAutoscalingSpec) {
	*out = *in
	in.AutoscalingSpec.DeepCopyInto(&out.AutoscalingSpec)
	if in.RPS != nil {
		in, out := &in.RPS, &out.RPS
		*out = new(RPSTrigger)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AppAutoscalingSpec.
func (in *AppAutoscalingSpec) DeepCopy() *AppAutoscalingSpec {
	if in == nil {
		return nil
	}
	out := new(AppAutoscalingSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AppSpec) DeepCopyInto(out *AppSpec) {
	*out = *in
	in.ComponentSpec.DeepCopyInto(&out.ComponentSpec)
	if in.Autoscaling != nil {
		in, out := &in.Autoscaling, &out.Autoscaling
		*out = new(AppAutoscalingSpec)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AppSpec.
func (in *AppSpec) DeepCopy() *AppSpec {
	if in == nil {
		return nil
	}
	out := new(AppSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AutoscalingSpec) DeepCopyInto(out *AutoscalingSpec) {
	*out = *in
	if in.MinReplicas != nil {
		in, out := &in.MinReplicas, &out.MinReplicas
		*out = new(int32)
		**out = **in
	}
	if in.TargetCPUUtilizationPercentage != nil {
		in, out := &in.TargetCPUUtilizationPercentage, &out.TargetCPUUtilizationPercentage
		*out = new(int32)
		**out = **in
	}
	if in.TargetMemoryUtilizationPercentage != nil {
		in, out := &in.TargetMemoryUtilizationPercentage, &out.TargetMemoryUtilizationPercentage
		*out = new(int32)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AutoscalingSpec.
func (in *AutoscalingSpec) DeepCopy() *AutoscalingSpec {
	if in == nil {
		return nil
	}
	out := new(AutoscalingSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *BackupStatus) DeepCopyInto(out *BackupStatus) {
	*out = *in
	in.LastSuccessfulBackup.DeepCopyInto(&out.LastSuccessfulBackup)
	in.FirstRecoverabilityPoint.DeepCopyInto(&out.FirstRecoverabilityPoint)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new BackupStatus.
func (in *BackupStatus) DeepCopy() *BackupStatus {
	if in == nil {
		return nil
	}
	out := new(BackupStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *BackupVerificationStatus) DeepCopyInto(out *BackupVerificationStatus) {
	*out = *in
	in.LastVerifiedTime.DeepCopyInto(&out.LastVerifiedTime)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new BackupVerificationStatus.
func (in *BackupVerificationStatus) DeepCopy() *BackupVerificationStatus {
	if in == nil {
		return nil
	}
	out := new(BackupVerificationStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *BackupVerify) DeepCopyInto(out *BackupVerify) {
	*out = *in
	out.Interval = in.Interval
	out.Timeout = in.Timeout
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new BackupVerify.
func (in *BackupVerify) DeepCopy() *BackupVerify {
	if in == nil {
		return nil
	}
	out := new(BackupVerify)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ChannelRollout) DeepCopyInto(out *ChannelRollout) {
	*out = *in
	out.Interval = in.Interval
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ChannelRollout.
func (in *ChannelRollout) DeepCopy() *ChannelRollout {
	if in == nil {
		return nil
	}
	out := new(ChannelRollout)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ComponentSpec) DeepCopyInto(out *ComponentSpec) {
	*out = *in
	if in.Replicas != nil {
		in, out := &in.Replicas, &out.Replicas
		*out = new(int32)
		**out = **in
	}
	in.Resources.DeepCopyInto(&out.Resources)
	if in.NodeSelector != nil {
		in, out := &in.NodeSelector, &out.NodeSelector
		*out = make(map[string]string, len(*in))
		for key, val := range *in {
			(*out)[key] = val
		}
	}
	if in.Tolerations != nil {
		in, out := &in.Tolerations, &out.Tolerations
		*out = make([]v1.Toleration, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ComponentSpec.
func (in *ComponentSpec) DeepCopy() *ComponentSpec {
	if in == nil {
		return nil
	}
	out := new(ComponentSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *EgressIsolationSpec) DeepCopyInto(out *EgressIsolationSpec) {
	*out = *in
	if in.Enabled != nil {
		in, out := &in.Enabled, &out.Enabled
		*out = new(bool)
		**out = **in
	}
	if in.AllowedNamespaces != nil {
		in, out := &in.AllowedNamespaces, &out.AllowedNamespaces
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new EgressIsolationSpec.
func (in *EgressIsolationSpec) DeepCopy() *EgressIsolationSpec {
	if in == nil {
		return nil
	}
	out := new(EgressIsolationSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ExternalMeilisearch) DeepCopyInto(out *ExternalMeilisearch) {
	*out = *in
	in.APIKeySecret.DeepCopyInto(&out.APIKeySecret)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ExternalMeilisearch.
func (in *ExternalMeilisearch) DeepCopy() *ExternalMeilisearch {
	if in == nil {
		return nil
	}
	out := new(ExternalMeilisearch)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ExternalPostgres) DeepCopyInto(out *ExternalPostgres) {
	*out = *in
	in.PasswordSecret.DeepCopyInto(&out.PasswordSecret)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ExternalPostgres.
func (in *ExternalPostgres) DeepCopy() *ExternalPostgres {
	if in == nil {
		return nil
	}
	out := new(ExternalPostgres)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ExternalRedis) DeepCopyInto(out *ExternalRedis) {
	*out = *in
	if in.PasswordSecret != nil {
		in, out := &in.PasswordSecret, &out.PasswordSecret
		*out = new(v1.SecretKeySelector)
		(*in).DeepCopyInto(*out)
	}
	if in.Sentinels != nil {
		in, out := &in.Sentinels, &out.Sentinels
		*out = make([]RedisHostPort, len(*in))
		copy(*out, *in)
	}
	if in.TLS != nil {
		in, out := &in.TLS, &out.TLS
		*out = new(bool)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ExternalRedis.
func (in *ExternalRedis) DeepCopy() *ExternalRedis {
	if in == nil {
		return nil
	}
	out := new(ExternalRedis)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *FilesSpec) DeepCopyInto(out *FilesSpec) {
	*out = *in
	if in.MaxFileSize != nil {
		in, out := &in.MaxFileSize, &out.MaxFileSize
		*out = new(int64)
		**out = **in
	}
	if in.ProxyRemoteFiles != nil {
		in, out := &in.ProxyRemoteFiles, &out.ProxyRemoteFiles
		*out = new(bool)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new FilesSpec.
func (in *FilesSpec) DeepCopy() *FilesSpec {
	if in == nil {
		return nil
	}
	out := new(FilesSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ImageFromSource) DeepCopyInto(out *ImageFromSource) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ImageFromSource.
func (in *ImageFromSource) DeepCopy() *ImageFromSource {
	if in == nil {
		return nil
	}
	out := new(ImageFromSource)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ImportSource) DeepCopyInto(out *ImportSource) {
	*out = *in
	in.PasswordSecret.DeepCopyInto(&out.PasswordSecret)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ImportSource.
func (in *ImportSource) DeepCopy() *ImportSource {
	if in == nil {
		return nil
	}
	out := new(ImportSource)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *IngressIssuerRef) DeepCopyInto(out *IngressIssuerRef) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new IngressIssuerRef.
func (in *IngressIssuerRef) DeepCopy() *IngressIssuerRef {
	if in == nil {
		return nil
	}
	out := new(IngressIssuerRef)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *IngressSpec) DeepCopyInto(out *IngressSpec) {
	*out = *in
	if in.Enabled != nil {
		in, out := &in.Enabled, &out.Enabled
		*out = new(bool)
		**out = **in
	}
	if in.Annotations != nil {
		in, out := &in.Annotations, &out.Annotations
		*out = make(map[string]string, len(*in))
		for key, val := range *in {
			(*out)[key] = val
		}
	}
	if in.IssuerRef != nil {
		in, out := &in.IssuerRef, &out.IssuerRef
		*out = new(IngressIssuerRef)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new IngressSpec.
func (in *IngressSpec) DeepCopy() *IngressSpec {
	if in == nil {
		return nil
	}
	out := new(IngressSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *LimitRangeSpec) DeepCopyInto(out *LimitRangeSpec) {
	*out = *in
	if in.Default != nil {
		in, out := &in.Default, &out.Default
		*out = make(v1.ResourceList, len(*in))
		for key, val := range *in {
			(*out)[key] = val.DeepCopy()
		}
	}
	if in.DefaultRequest != nil {
		in, out := &in.DefaultRequest, &out.DefaultRequest
		*out = make(v1.ResourceList, len(*in))
		for key, val := range *in {
			(*out)[key] = val.DeepCopy()
		}
	}
	if in.Max != nil {
		in, out := &in.Max, &out.Max
		*out = make(v1.ResourceList, len(*in))
		for key, val := range *in {
			(*out)[key] = val.DeepCopy()
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new LimitRangeSpec.
func (in *LimitRangeSpec) DeepCopy() *LimitRangeSpec {
	if in == nil {
		return nil
	}
	out := new(LimitRangeSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *MaintenanceSpec) DeepCopyInto(out *MaintenanceSpec) {
	*out = *in
	if in.Enabled != nil {
		in, out := &in.Enabled, &out.Enabled
		*out = new(bool)
		**out = **in
	}
	if in.StatusCode != nil {
		in, out := &in.StatusCode, &out.StatusCode
		*out = new(int32)
		**out = **in
	}
	if in.ReloadSeconds != nil {
		in, out := &in.ReloadSeconds, &out.ReloadSeconds
		*out = new(int32)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new MaintenanceSpec.
func (in *MaintenanceSpec) DeepCopy() *MaintenanceSpec {
	if in == nil {
		return nil
	}
	out := new(MaintenanceSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *MeilisearchSpec) DeepCopyInto(out *MeilisearchSpec) {
	*out = *in
	if in.External != nil {
		in, out := &in.External, &out.External
		*out = new(ExternalMeilisearch)
		(*in).DeepCopyInto(*out)
	}
	out.Storage = in.Storage.DeepCopy()
	if in.StorageClassName != nil {
		in, out := &in.StorageClassName, &out.StorageClassName
		*out = new(string)
		**out = **in
	}
	if in.MasterKeySecret != nil {
		in, out := &in.MasterKeySecret, &out.MasterKeySecret
		*out = new(v1.SecretKeySelector)
		(*in).DeepCopyInto(*out)
	}
	in.Resources.DeepCopyInto(&out.Resources)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new MeilisearchSpec.
func (in *MeilisearchSpec) DeepCopy() *MeilisearchSpec {
	if in == nil {
		return nil
	}
	out := new(MeilisearchSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *MigrationSpec) DeepCopyInto(out *MigrationSpec) {
	*out = *in
	if in.CreateIndexConcurrently != nil {
		in, out := &in.CreateIndexConcurrently, &out.CreateIndexConcurrently
		*out = new(bool)
		**out = **in
	}
	if in.PreBackup != nil {
		in, out := &in.PreBackup, &out.PreBackup
		*out = new(bool)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new MigrationSpec.
func (in *MigrationSpec) DeepCopy() *MigrationSpec {
	if in == nil {
		return nil
	}
	out := new(MigrationSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *Misskey) DeepCopyInto(out *Misskey) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new Misskey.
func (in *Misskey) DeepCopy() *Misskey {
	if in == nil {
		return nil
	}
	out := new(Misskey)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *Misskey) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *MisskeyChannel) DeepCopyInto(out *MisskeyChannel) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new MisskeyChannel.
func (in *MisskeyChannel) DeepCopy() *MisskeyChannel {
	if in == nil {
		return nil
	}
	out := new(MisskeyChannel)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *MisskeyChannel) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *MisskeyChannelList) DeepCopyInto(out *MisskeyChannelList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]MisskeyChannel, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new MisskeyChannelList.
func (in *MisskeyChannelList) DeepCopy() *MisskeyChannelList {
	if in == nil {
		return nil
	}
	out := new(MisskeyChannelList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *MisskeyChannelList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *MisskeyChannelSpec) DeepCopyInto(out *MisskeyChannelSpec) {
	*out = *in
	if in.Rollout != nil {
		in, out := &in.Rollout, &out.Rollout
		*out = new(ChannelRollout)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new MisskeyChannelSpec.
func (in *MisskeyChannelSpec) DeepCopy() *MisskeyChannelSpec {
	if in == nil {
		return nil
	}
	out := new(MisskeyChannelSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *MisskeyChannelStatus) DeepCopyInto(out *MisskeyChannelStatus) {
	*out = *in
	in.ImageChangedAt.DeepCopyInto(&out.ImageChangedAt)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new MisskeyChannelStatus.
func (in *MisskeyChannelStatus) DeepCopy() *MisskeyChannelStatus {
	if in == nil {
		return nil
	}
	out := new(MisskeyChannelStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *MisskeyList) DeepCopyInto(out *MisskeyList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]Misskey, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new MisskeyList.
func (in *MisskeyList) DeepCopy() *MisskeyList {
	if in == nil {
		return nil
	}
	out := new(MisskeyList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *MisskeyList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *MisskeySpec) DeepCopyInto(out *MisskeySpec) {
	*out = *in
	if in.ImageFrom != nil {
		in, out := &in.ImageFrom, &out.ImageFrom
		*out = new(ImageFromSource)
		**out = **in
	}
	if in.ImagePullSecrets != nil {
		in, out := &in.ImagePullSecrets, &out.ImagePullSecrets
		*out = make([]v1.LocalObjectReference, len(*in))
		copy(*out, *in)
	}
	in.Runtime.DeepCopyInto(&out.Runtime)
	in.App.DeepCopyInto(&out.App)
	in.Worker.DeepCopyInto(&out.Worker)
	in.Proxy.DeepCopyInto(&out.Proxy)
	in.Ingress.DeepCopyInto(&out.Ingress)
	in.Redis.DeepCopyInto(&out.Redis)
	in.Search.DeepCopyInto(&out.Search)
	in.Postgres.DeepCopyInto(&out.Postgres)
	in.Migration.DeepCopyInto(&out.Migration)
	if in.SetupPassword != nil {
		in, out := &in.SetupPassword, &out.SetupPassword
		*out = new(SetupPasswordSpec)
		(*in).DeepCopyInto(*out)
	}
	if in.ObjectStorage != nil {
		in, out := &in.ObjectStorage, &out.ObjectStorage
		*out = new(ObjectStorageSpec)
		(*in).DeepCopyInto(*out)
	}
	in.Network.DeepCopyInto(&out.Network)
	in.Tenancy.DeepCopyInto(&out.Tenancy)
	in.Monitoring.DeepCopyInto(&out.Monitoring)
	in.Performance.DeepCopyInto(&out.Performance)
	in.OutboundProxy.DeepCopyInto(&out.OutboundProxy)
	in.Files.DeepCopyInto(&out.Files)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new MisskeySpec.
func (in *MisskeySpec) DeepCopy() *MisskeySpec {
	if in == nil {
		return nil
	}
	out := new(MisskeySpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *MisskeyStatus) DeepCopyInto(out *MisskeyStatus) {
	*out = *in
	if in.Conditions != nil {
		in, out := &in.Conditions, &out.Conditions
		*out = make([]metav1.Condition, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.BackupVerification != nil {
		in, out := &in.BackupVerification, &out.BackupVerification
		*out = new(BackupVerificationStatus)
		(*in).DeepCopyInto(*out)
	}
	if in.Backup != nil {
		in, out := &in.Backup, &out.Backup
		*out = new(BackupStatus)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new MisskeyStatus.
func (in *MisskeyStatus) DeepCopy() *MisskeyStatus {
	if in == nil {
		return nil
	}
	out := new(MisskeyStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *MonitoringRules) DeepCopyInto(out *MonitoringRules) {
	*out = *in
	if in.Enabled != nil {
		in, out := &in.Enabled, &out.Enabled
		*out = new(bool)
		**out = **in
	}
	out.BackupMaxAge = in.BackupMaxAge
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new MonitoringRules.
func (in *MonitoringRules) DeepCopy() *MonitoringRules {
	if in == nil {
		return nil
	}
	out := new(MonitoringRules)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *MonitoringSpec) DeepCopyInto(out *MonitoringSpec) {
	*out = *in
	if in.Enabled != nil {
		in, out := &in.Enabled, &out.Enabled
		*out = new(bool)
		**out = **in
	}
	if in.Labels != nil {
		in, out := &in.Labels, &out.Labels
		*out = make(map[string]string, len(*in))
		for key, val := range *in {
			(*out)[key] = val
		}
	}
	if in.Rules != nil {
		in, out := &in.Rules, &out.Rules
		*out = new(MonitoringRules)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new MonitoringSpec.
func (in *MonitoringSpec) DeepCopy() *MonitoringSpec {
	if in == nil {
		return nil
	}
	out := new(MonitoringSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *NetworkIsolationSpec) DeepCopyInto(out *NetworkIsolationSpec) {
	*out = *in
	if in.Enabled != nil {
		in, out := &in.Enabled, &out.Enabled
		*out = new(bool)
		**out = **in
	}
	if in.AllowedNamespaces != nil {
		in, out := &in.AllowedNamespaces, &out.AllowedNamespaces
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new NetworkIsolationSpec.
func (in *NetworkIsolationSpec) DeepCopy() *NetworkIsolationSpec {
	if in == nil {
		return nil
	}
	out := new(NetworkIsolationSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *NetworkSpec) DeepCopyInto(out *NetworkSpec) {
	*out = *in
	in.Isolation.DeepCopyInto(&out.Isolation)
	in.EgressIsolation.DeepCopyInto(&out.EgressIsolation)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new NetworkSpec.
func (in *NetworkSpec) DeepCopy() *NetworkSpec {
	if in == nil {
		return nil
	}
	out := new(NetworkSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ObjectStorageColumns) DeepCopyInto(out *ObjectStorageColumns) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ObjectStorageColumns.
func (in *ObjectStorageColumns) DeepCopy() *ObjectStorageColumns {
	if in == nil {
		return nil
	}
	out := new(ObjectStorageColumns)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ObjectStorageSpec) DeepCopyInto(out *ObjectStorageSpec) {
	*out = *in
	if in.Port != nil {
		in, out := &in.Port, &out.Port
		*out = new(int32)
		**out = **in
	}
	if in.UseSSL != nil {
		in, out := &in.UseSSL, &out.UseSSL
		*out = new(bool)
		**out = **in
	}
	if in.UseProxy != nil {
		in, out := &in.UseProxy, &out.UseProxy
		*out = new(bool)
		**out = **in
	}
	if in.SetPublicRead != nil {
		in, out := &in.SetPublicRead, &out.SetPublicRead
		*out = new(bool)
		**out = **in
	}
	if in.S3ForcePathStyle != nil {
		in, out := &in.S3ForcePathStyle, &out.S3ForcePathStyle
		*out = new(bool)
		**out = **in
	}
	in.Credentials.DeepCopyInto(&out.Credentials)
	if in.AutoConfigure != nil {
		in, out := &in.AutoConfigure, &out.AutoConfigure
		*out = new(bool)
		**out = **in
	}
	if in.ColumnNames != nil {
		in, out := &in.ColumnNames, &out.ColumnNames
		*out = new(ObjectStorageColumns)
		**out = **in
	}
	if in.ExtraColumns != nil {
		in, out := &in.ExtraColumns, &out.ExtraColumns
		*out = make(map[string]string, len(*in))
		for key, val := range *in {
			(*out)[key] = val
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ObjectStorageSpec.
func (in *ObjectStorageSpec) DeepCopy() *ObjectStorageSpec {
	if in == nil {
		return nil
	}
	out := new(ObjectStorageSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *OutboundProxySpec) DeepCopyInto(out *OutboundProxySpec) {
	*out = *in
	if in.BypassHosts != nil {
		in, out := &in.BypassHosts, &out.BypassHosts
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new OutboundProxySpec.
func (in *OutboundProxySpec) DeepCopy() *OutboundProxySpec {
	if in == nil {
		return nil
	}
	out := new(OutboundProxySpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PerformanceSpec) DeepCopyInto(out *PerformanceSpec) {
	*out = *in
	if in.DeliverJobConcurrency != nil {
		in, out := &in.DeliverJobConcurrency, &out.DeliverJobConcurrency
		*out = new(int32)
		**out = **in
	}
	if in.InboxJobConcurrency != nil {
		in, out := &in.InboxJobConcurrency, &out.InboxJobConcurrency
		*out = new(int32)
		**out = **in
	}
	if in.DeliverJobPerSec != nil {
		in, out := &in.DeliverJobPerSec, &out.DeliverJobPerSec
		*out = new(int32)
		**out = **in
	}
	if in.InboxJobPerSec != nil {
		in, out := &in.InboxJobPerSec, &out.InboxJobPerSec
		*out = new(int32)
		**out = **in
	}
	if in.RelationshipJobPerSec != nil {
		in, out := &in.RelationshipJobPerSec, &out.RelationshipJobPerSec
		*out = new(int32)
		**out = **in
	}
	if in.DeliverJobMaxAttempts != nil {
		in, out := &in.DeliverJobMaxAttempts, &out.DeliverJobMaxAttempts
		*out = new(int32)
		**out = **in
	}
	if in.InboxJobMaxAttempts != nil {
		in, out := &in.InboxJobMaxAttempts, &out.InboxJobMaxAttempts
		*out = new(int32)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PerformanceSpec.
func (in *PerformanceSpec) DeepCopy() *PerformanceSpec {
	if in == nil {
		return nil
	}
	out := new(PerformanceSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PostgresBackup) DeepCopyInto(out *PostgresBackup) {
	*out = *in
	if in.S3Credentials != nil {
		in, out := &in.S3Credentials, &out.S3Credentials
		*out = new(S3Credentials)
		(*in).DeepCopyInto(*out)
	}
	if in.Verify != nil {
		in, out := &in.Verify, &out.Verify
		*out = new(BackupVerify)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PostgresBackup.
func (in *PostgresBackup) DeepCopy() *PostgresBackup {
	if in == nil {
		return nil
	}
	out := new(PostgresBackup)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PostgresImport) DeepCopyInto(out *PostgresImport) {
	*out = *in
	in.Source.DeepCopyInto(&out.Source)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PostgresImport.
func (in *PostgresImport) DeepCopy() *PostgresImport {
	if in == nil {
		return nil
	}
	out := new(PostgresImport)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PostgresPooler) DeepCopyInto(out *PostgresPooler) {
	*out = *in
	if in.Parameters != nil {
		in, out := &in.Parameters, &out.Parameters
		*out = make(map[string]string, len(*in))
		for key, val := range *in {
			(*out)[key] = val
		}
	}
	in.Resources.DeepCopyInto(&out.Resources)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PostgresPooler.
func (in *PostgresPooler) DeepCopy() *PostgresPooler {
	if in == nil {
		return nil
	}
	out := new(PostgresPooler)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PostgresRecovery) DeepCopyInto(out *PostgresRecovery) {
	*out = *in
	in.Source.DeepCopyInto(&out.Source)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PostgresRecovery.
func (in *PostgresRecovery) DeepCopy() *PostgresRecovery {
	if in == nil {
		return nil
	}
	out := new(PostgresRecovery)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PostgresSpec) DeepCopyInto(out *PostgresSpec) {
	*out = *in
	if in.External != nil {
		in, out := &in.External, &out.External
		*out = new(ExternalPostgres)
		(*in).DeepCopyInto(*out)
	}
	out.Storage = in.Storage.DeepCopy()
	if in.StorageClassName != nil {
		in, out := &in.StorageClassName, &out.StorageClassName
		*out = new(string)
		**out = **in
	}
	if in.Parameters != nil {
		in, out := &in.Parameters, &out.Parameters
		*out = make(map[string]string, len(*in))
		for key, val := range *in {
			(*out)[key] = val
		}
	}
	in.Resources.DeepCopyInto(&out.Resources)
	if in.Backup != nil {
		in, out := &in.Backup, &out.Backup
		*out = new(PostgresBackup)
		(*in).DeepCopyInto(*out)
	}
	if in.Recovery != nil {
		in, out := &in.Recovery, &out.Recovery
		*out = new(PostgresRecovery)
		(*in).DeepCopyInto(*out)
	}
	if in.Import != nil {
		in, out := &in.Import, &out.Import
		*out = new(PostgresImport)
		(*in).DeepCopyInto(*out)
	}
	if in.ReadOffload != nil {
		in, out := &in.ReadOffload, &out.ReadOffload
		*out = new(bool)
		**out = **in
	}
	if in.Pooler != nil {
		in, out := &in.Pooler, &out.Pooler
		*out = new(PostgresPooler)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PostgresSpec.
func (in *PostgresSpec) DeepCopy() *PostgresSpec {
	if in == nil {
		return nil
	}
	out := new(PostgresSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ProxySpec) DeepCopyInto(out *ProxySpec) {
	*out = *in
	if in.Enabled != nil {
		in, out := &in.Enabled, &out.Enabled
		*out = new(bool)
		**out = **in
	}
	if in.Replicas != nil {
		in, out := &in.Replicas, &out.Replicas
		*out = new(int32)
		**out = **in
	}
	in.Maintenance.DeepCopyInto(&out.Maintenance)
	in.Resources.DeepCopyInto(&out.Resources)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ProxySpec.
func (in *ProxySpec) DeepCopy() *ProxySpec {
	if in == nil {
		return nil
	}
	out := new(ProxySpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *QueueScaleTrigger) DeepCopyInto(out *QueueScaleTrigger) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new QueueScaleTrigger.
func (in *QueueScaleTrigger) DeepCopy() *QueueScaleTrigger {
	if in == nil {
		return nil
	}
	out := new(QueueScaleTrigger)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *RPSTrigger) DeepCopyInto(out *RPSTrigger) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new RPSTrigger.
func (in *RPSTrigger) DeepCopy() *RPSTrigger {
	if in == nil {
		return nil
	}
	out := new(RPSTrigger)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *RecoverySource) DeepCopyInto(out *RecoverySource) {
	*out = *in
	if in.S3Credentials != nil {
		in, out := &in.S3Credentials, &out.S3Credentials
		*out = new(S3Credentials)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new RecoverySource.
func (in *RecoverySource) DeepCopy() *RecoverySource {
	if in == nil {
		return nil
	}
	out := new(RecoverySource)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *RedisHA) DeepCopyInto(out *RedisHA) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new RedisHA.
func (in *RedisHA) DeepCopy() *RedisHA {
	if in == nil {
		return nil
	}
	out := new(RedisHA)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *RedisHostPort) DeepCopyInto(out *RedisHostPort) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new RedisHostPort.
func (in *RedisHostPort) DeepCopy() *RedisHostPort {
	if in == nil {
		return nil
	}
	out := new(RedisHostPort)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *RedisRole) DeepCopyInto(out *RedisRole) {
	*out = *in
	if in.External != nil {
		in, out := &in.External, &out.External
		*out = new(ExternalRedis)
		(*in).DeepCopyInto(*out)
	}
	out.Storage = in.Storage.DeepCopy()
	if in.StorageClassName != nil {
		in, out := &in.StorageClassName, &out.StorageClassName
		*out = new(string)
		**out = **in
	}
	in.Resources.DeepCopyInto(&out.Resources)
	if in.HA != nil {
		in, out := &in.HA, &out.HA
		*out = new(RedisHA)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new RedisRole.
func (in *RedisRole) DeepCopy() *RedisRole {
	if in == nil {
		return nil
	}
	out := new(RedisRole)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *RedisRoles) DeepCopyInto(out *RedisRoles) {
	*out = *in
	if in.JobQueue != nil {
		in, out := &in.JobQueue, &out.JobQueue
		*out = new(RedisRole)
		(*in).DeepCopyInto(*out)
	}
	if in.Pubsub != nil {
		in, out := &in.Pubsub, &out.Pubsub
		*out = new(RedisRole)
		(*in).DeepCopyInto(*out)
	}
	if in.Timelines != nil {
		in, out := &in.Timelines, &out.Timelines
		*out = new(RedisRole)
		(*in).DeepCopyInto(*out)
	}
	if in.Reactions != nil {
		in, out := &in.Reactions, &out.Reactions
		*out = new(RedisRole)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new RedisRoles.
func (in *RedisRoles) DeepCopy() *RedisRoles {
	if in == nil {
		return nil
	}
	out := new(RedisRoles)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *RedisSpec) DeepCopyInto(out *RedisSpec) {
	*out = *in
	if in.External != nil {
		in, out := &in.External, &out.External
		*out = new(ExternalRedis)
		(*in).DeepCopyInto(*out)
	}
	if in.AppendOnly != nil {
		in, out := &in.AppendOnly, &out.AppendOnly
		*out = new(bool)
		**out = **in
	}
	out.Storage = in.Storage.DeepCopy()
	if in.StorageClassName != nil {
		in, out := &in.StorageClassName, &out.StorageClassName
		*out = new(string)
		**out = **in
	}
	in.Resources.DeepCopyInto(&out.Resources)
	if in.HA != nil {
		in, out := &in.HA, &out.HA
		*out = new(RedisHA)
		**out = **in
	}
	if in.Roles != nil {
		in, out := &in.Roles, &out.Roles
		*out = new(RedisRoles)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new RedisSpec.
func (in *RedisSpec) DeepCopy() *RedisSpec {
	if in == nil {
		return nil
	}
	out := new(RedisSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *RuntimeSpec) DeepCopyInto(out *RuntimeSpec) {
	*out = *in
	if in.RunAsUser != nil {
		in, out := &in.RunAsUser, &out.RunAsUser
		*out = new(int64)
		**out = **in
	}
	if in.StartCommand != nil {
		in, out := &in.StartCommand, &out.StartCommand
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.MigrateCommand != nil {
		in, out := &in.MigrateCommand, &out.MigrateCommand
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.BuiltPath != nil {
		in, out := &in.BuiltPath, &out.BuiltPath
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new RuntimeSpec.
func (in *RuntimeSpec) DeepCopy() *RuntimeSpec {
	if in == nil {
		return nil
	}
	out := new(RuntimeSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *S3Credentials) DeepCopyInto(out *S3Credentials) {
	*out = *in
	in.AccessKeyID.DeepCopyInto(&out.AccessKeyID)
	in.SecretAccessKey.DeepCopyInto(&out.SecretAccessKey)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new S3Credentials.
func (in *S3Credentials) DeepCopy() *S3Credentials {
	if in == nil {
		return nil
	}
	out := new(S3Credentials)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SearchSpec) DeepCopyInto(out *SearchSpec) {
	*out = *in
	in.Meilisearch.DeepCopyInto(&out.Meilisearch)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SearchSpec.
func (in *SearchSpec) DeepCopy() *SearchSpec {
	if in == nil {
		return nil
	}
	out := new(SearchSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SetupPasswordSpec) DeepCopyInto(out *SetupPasswordSpec) {
	*out = *in
	if in.SecretRef != nil {
		in, out := &in.SecretRef, &out.SecretRef
		*out = new(v1.SecretKeySelector)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SetupPasswordSpec.
func (in *SetupPasswordSpec) DeepCopy() *SetupPasswordSpec {
	if in == nil {
		return nil
	}
	out := new(SetupPasswordSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *TenancySpec) DeepCopyInto(out *TenancySpec) {
	*out = *in
	if in.Quota != nil {
		in, out := &in.Quota, &out.Quota
		*out = make(v1.ResourceList, len(*in))
		for key, val := range *in {
			(*out)[key] = val.DeepCopy()
		}
	}
	if in.LimitRange != nil {
		in, out := &in.LimitRange, &out.LimitRange
		*out = new(LimitRangeSpec)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new TenancySpec.
func (in *TenancySpec) DeepCopy() *TenancySpec {
	if in == nil {
		return nil
	}
	out := new(TenancySpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *WorkerAutoscalingSpec) DeepCopyInto(out *WorkerAutoscalingSpec) {
	*out = *in
	in.AutoscalingSpec.DeepCopyInto(&out.AutoscalingSpec)
	if in.Queues != nil {
		in, out := &in.Queues, &out.Queues
		*out = make([]QueueScaleTrigger, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new WorkerAutoscalingSpec.
func (in *WorkerAutoscalingSpec) DeepCopy() *WorkerAutoscalingSpec {
	if in == nil {
		return nil
	}
	out := new(WorkerAutoscalingSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *WorkerSpec) DeepCopyInto(out *WorkerSpec) {
	*out = *in
	in.ComponentSpec.DeepCopyInto(&out.ComponentSpec)
	if in.Autoscaling != nil {
		in, out := &in.Autoscaling, &out.Autoscaling
		*out = new(WorkerAutoscalingSpec)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new WorkerSpec.
func (in *WorkerSpec) DeepCopy() *WorkerSpec {
	if in == nil {
		return nil
	}
	out := new(WorkerSpec)
	in.DeepCopyInto(out)
	return out
}
